# 数据路径相关==============================
classes_path: config/voc_classes.txt
train_ann_path: config/2007_train.txt
val_ann_path: config/2007_val.txt
input_shape: [ 640,640 ]
train_dataset: F:\GtiEE\yolo_pandora\datasets\coco_data\images\train2017
train_json_path: F:\GtiEE\yolo_pandora\datasets\coco_data\annotations\instances_train2017.json
val_dataset: F:\GtiEE\yolo_pandora\datasets\coco_data\images\train2017
val_json_path: F:\GtiEE\yolo_pandora\datasets\coco_data\annotations\instances_val2017.json

#train_dataset: I:\gitEE\yolo_pandora\datasets\coco_data\images\train2017
#train_json_path: I:\gitEE\yolo_pandora\datasets\coco_data\annotations\instances_train2017.json
#val_dataset: I:\gitEE\yolo_pandora\datasets\coco_data\images\train2017
#val_json_path: I:\gitEE\yolo_pandora\datasets\coco_data\annotations\instances_val2017.json
# ========================================

# 可选:None,cpu. 为None时,自动搜索设备,优先使用gpu
device: None
# 网络结构选择==============================
# phi只能从nano,tiny,s,m,l,x中选择,phi只在cspdarknet中生效,其他backbone不调用
phi: s
# depth:调整csp模块bottleneck(残差块)数量, width:调整所有卷积层通道数, 此处None为占位符,
# 具体值在yolo_util.transfer根据l重新赋值
depth: None
width: None
# depth_wise,是否使用深度可分离卷积,也由phi决定,此处仅占位
depth_wise: None
activation: silu

# **********************************************************
# backbone可选项:csp_darknet,darknet
# neck可选项:pa_fpn,      ,  head可选项:decoupled_head
backbone: csp_darknet
neck: pa_fpn
head: decoupled_head

optimizer: yolox_optimizer
# IouLoss,AlphaIouLoss,IouLoss
iou_loss: IouLoss
# **********************************************************


# 是否使用预训练模型
resume: True
model_path: weights/yolox_s.pth
lrf: 0.01
warmup_epochs: 3
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr

# 模型训练相关
batch_sz: 4

# 模型结构相关===============================
# 指定模型规格,l是正常模型大小
mosaic: False
cosine: False
num_classes: None   # 占位符,在yolo_utils.transfer中根据classes类别数量自动重新赋值
classes: [
  "aeroplane",
  "bicycle",
  "bird",
  "boat",
  "bottle",
  "bus",
  "car",
  "cat",
  "chair",
  "cow",
  "diningtable",
  "dog",
  "horse",
  "motorbike",
  "person",
  "pottedplant",
  "sheep",
  "sofa",
  "train",
  "tvmonitor", ]
# ========================================

